from . import (
    cpu,
    memory,
    disk,
    network,
    osinfo,
    packages,
    processes,
    logs,
    env,
    docker,
    python,
    services,
    crontab,
    users,
    hardware,
    kernelmods,
    limits,
    firewall,
    mounts,
    netconns,
)

ALL_COLLECTORS = {
    "cpu": cpu,
    "memory": memory,
    "disk": disk,
    "network": network,
    "osinfo": osinfo,
    "packages": packages,
    "processes": processes,
    "logs": logs,
    "env": env,
    "docker": docker,
    "python": python,
    "services": services,
    "crontab": crontab,
    "users": users,
    "hardware": hardware,
    "kernelmods": kernelmods,
    "limits": limits,
    "firewall": firewall,
    "mounts": mounts,
    "netconns": netconns,
}
